apiVersion: v1
kind: Secret
metadata:
  name: user-vault-secret
type: Opaque
stringData:
  # Cipher keys
  AES_SECRET_ENCRYPTION_ENABLED: "false" # options: "true", "false"
  AES_SECRET_KEY: "" # if AES_CIPHER_SECRET_ENCRYPTION_ENABLED is true, must be 16, 24, or 32 bytes long

  # JWT Config
  JWT_METHOD: "HS256" # options: HS256, RS256
  JWT_HMAC_KEY: "supersecretkeyforhmac" # used if JWT_METHOD is HS256
  JWT_RSA_PRIVATE_KEY_PATH: "" # used if JWT_METHOD is RS256
  JWT_RSA_PUBLIC_KEY_PATH: "" # used if JWT_METHOD is RS256

  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USERNAME: "admin"
  DB_PASSWORD: "admin123"
  DB_NAME: "userVault"
  DB_PREFIX: "uv_"

  # Kafka configuration
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_USER_VERIFY_TOPIC: "user-verification"
  KAFKA_PASSWORD_RESET_TOPIC: "user-password-reset"
  KAFKA_CLIENT_ID: "user-vault"
  KAFKA_VERSION: "2.6.0"
  KAFKA_RETRY_MAX: "5"

